version: '2'

services:
  dbms:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: 1234qwer
    ports:
      - "5432:5432"

  fiscal_000:
    build: ../../../fiscal
    links:
      - dbms
        #    env_file:
        #      - ./config.env
    environment:
      MS_DBMS_HOST: "dbms"
      MS_DBMS_PORT: "5432"
      MS_PROFILE: "default.json"
      MS_DEBUG: "debug"
      MS_PORT: "10080"

  frontend_000:
    build: ../../../frontend
    links:
      - dbms
      - fiscal_000
        #    env_file:
        #- ./config.env
    environment:
      MS_DBMS_URL: "jdbc:postgresql://dbms:5432/${MS_DBMS_DB}"
      MS_FISCAL_HOST: "fiscal_000:10080"
    ports:
      - "8080:8080"
